In [602]:
#Pandas--------->Data handling
# 1D-------series

# 2D----------->Dataframe

In [603]:
#Series
import pandas as pd
import numpy as np

In [604]:
list1=[10,20,30,40,50]
a1=np.array(list1)
print(type(a1))

<class 'numpy.ndarray'>


In [605]:
a1

array([10, 20, 30, 40, 50])

In [606]:
a1.shape

(5,)

In [607]:
#np.random.randn(1000)

In [608]:
p1=pd.Series(list1)
print(type(p1))

<class 'pandas.core.series.Series'>


In [609]:
p1

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [610]:
p1.shape

(5,)

In [611]:
p1.index=["A","B","C","D","E"]

In [612]:
p1

A    10
B    20
C    30
D    40
E    50
dtype: int64

In [613]:
#Access the elemnt in pandas
# loc------ Accsse the element based on index label

# iloc------> Access the element based on index

In [614]:
#use loc
p1.loc["A":"C"]

A    10
B    20
C    30
dtype: int64

In [615]:
p1.iloc[0:3]

A    10
B    20
C    30
dtype: int64

In [616]:
p1.loc[["A","C","E"]]

A    10
C    30
E    50
dtype: int64

In [617]:
p1.iloc[[0,2,4]]

A    10
C    30
E    50
dtype: int64

In [618]:
#create a random 5 integers numbers from 10,100
#caslulate the square the each number
# make the corresponding integer number as a indexlabel value

In [619]:
np.random.seed(10)
ar=np.random.randint(10,100,5)
print(ar)

# 1. Random float in [0, 1)
print(np.random.rand())          # Single float
print(np.random.rand(3, 2))      # 3x2 array of random floats

# 2. Random integers
np.random.randint(10)             # Integer from 0 to 9
np.random.randint(5, 15, 4)       # 4 integers from 5 to 14

# 3. Standard normal distribution (mean=0, std=1)
print(np.random.randn())         # Single float
print(np.random.randn(2, 3))     # 2x3 array

# 4. Random sample from 1D array
arr = [1, 2, 3, 4]
np.random.choice(arr, 2)  # Pick 2 random elements

# 5. Shuffle array in-place
a = np.array([1, 2, 3, 4])
np.random.shuffle(a)

# 6. Permutation (returns a shuffled copy)
b = np.random.permutation([1, 2, 3, 4])
print(b)

# 7. Random numbers from uniform distribution
np.random.uniform(1, 10, 5)  # 5 floats between 1 and 10

# 8. Random numbers from normal distribution
np.random.normal(loc=0, scale=1, size=5)  # mean=0, std=1, 5 numbers

# 9. Set random seed (for reproducibility)
np.random.seed(42)

[19 25 74 38 99]
0.5833217369377363
[[0.02517173 0.70920801]
 [0.26556613 0.26360285]
 [0.15037787 0.68381843]]
0.36624857810678163
[[ 0.60808856 -1.08684028  0.12055902]
 [ 1.40202525 -0.4342591  -1.25424191]]
[1 2 3 4]


In [620]:
p2=pd.Series(ar)
p2=p2**2
p2

0     361
1     625
2    5476
3    1444
4    9801
dtype: int32

In [621]:
p2.index=ar
p2

19     361
25     625
74    5476
38    1444
99    9801
dtype: int32

# Dataframe---2D (Row and columns)

In [622]:
# Dataframe can be created from

# 1.Dictionary

# 2.list

# 3.array

In [623]:
# Dictionary

dictt={"Customer_ID": ["cust1","cust2","cust3","cust4","cust5","cust6","cust7"],"Item_Name":["Mobile","Laptop","Watch","Laptop","watch","Mobile","Mobile"],
       "Quantity":[2,1,5,6,2,1,7],"unit_price":[7000,4000,2000,1500,5000,8000,1000],"Discount":[0.1,0.05,0.03,0.04,0.01,0.1,0.3],
       "Profit":[0.15,0.2,0.18,0.08,0.15,0.1,0.2]}

sale_data=pd.DataFrame(dictt)
sale_data

,Customer_ID,Item_Name,Quantity,unit_price,Discount,Profit
0,cust1,Mobile,2,7000,0.10,0.15
1,cust2,Laptop,1,4000,0.05,0.20
2,cust3,Watch,5,2000,0.03,0.18
3,cust4,Laptop,6,1500,0.04,0.08
4,cust5,watch,2,5000,0.01,0.15
5,cust6,Mobile,1,8000,0.10,0.10
6,cust7,Mobile,7,1000,0.30,0.20


In [624]:
sale_data.columns
sale_data.index
sale_data.shape
sale_data.dtypes
sale_data.info()
sale_data.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Customer_ID  7 non-null      object 
 1   Item_Name    7 non-null      object 
 2   Quantity     7 non-null      int64  
 3   unit_price   7 non-null      int64  
 4   Discount     7 non-null      float64
 5   Profit       7 non-null      float64
dtypes: float64(2), int64(2), object(2)
memory usage: 468.0+ bytes


,Quantity,unit_price,Discount,Profit
count,7.000000,7.000000,7.000000,7.000000
mean,3.428571,4071.428571,0.090000,0.151429
std,2.507133,2745.125550,0.098658,0.047056
min,1.000000,1000.000000,0.010000,0.080000
25%,1.500000,1750.000000,0.035000,0.125000
50%,2.000000,4000.000000,0.050000,0.150000
75%,5.500000,6000.000000,0.100000,0.190000
max,7.000000,8000.000000,0.300000,0.200000


In [625]:
type(sale_data)

pandas.core.frame.DataFrame

In [626]:
sale_data.shape

(7, 6)

In [627]:
sale_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Customer_ID  7 non-null      object 
 1   Item_Name    7 non-null      object 
 2   Quantity     7 non-null      int64  
 3   unit_price   7 non-null      int64  
 4   Discount     7 non-null      float64
 5   Profit       7 non-null      float64
dtypes: float64(2), int64(2), object(2)
memory usage: 468.0+ bytes


In [628]:
#using list
sale_data_ls=pd.DataFrame([["cust1","Mobile",2,7000,0.10,0.15],["cust2","Laptop",1,4000,0.05,0.20],["cust3","Watch",5,2000,0.03,0.18]],
                          columns=['Customer_ID', 'Item_Name', 'Quantity', 'unit_price', 'Discount','Profit'])
sale_data_ls


,Customer_ID,Item_Name,Quantity,unit_price,Discount,Profit
0,cust1,Mobile,2,7000,0.10,0.15
1,cust2,Laptop,1,4000,0.05,0.20
2,cust3,Watch,5,2000,0.03,0.18


In [629]:
#sale_data_ls.info()

In [630]:
#Dataframe using numpy array
arr_data=np.array([["cust1","Mobile",2,7000,0.10,0.15],["cust2","Laptop",1,4000,0.05,0.20],["cust3","Watch",5,2000,0.03,0.18]])
arr_df=pd.DataFrame(arr_data,columns=['Customer_ID', 'Item_Name', 'Quantity', 'unit_price', 'Discount','Profit'])
arr_df

,Customer_ID,Item_Name,Quantity,unit_price,Discount,Profit
0,cust1,Mobile,2,7000,0.1,0.15
1,cust2,Laptop,1,4000,0.05,0.2
2,cust3,Watch,5,2000,0.03,0.18


In [631]:
arr_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   Customer_ID  3 non-null      object
 1   Item_Name    3 non-null      object
 2   Quantity     3 non-null      object
 3   unit_price   3 non-null      object
 4   Discount     3 non-null      object
 5   Profit       3 non-null      object
dtypes: object(6)
memory usage: 276.0+ bytes


In [632]:
x=np.array([10,20.1,30,40,50])
print(x)
print(x.dtype)

[10.  20.1 30.  40.  50. ]
float64


In [633]:
list1=[10,20.1,30,40,50,"True"]
print(list1)

[10, 20.1, 30, 40, 50, 'True']


In [634]:
10.0+10.0+20.5

40.5

In [635]:
10+10+20.5

40.5

In [636]:
sale_data

,Customer_ID,Item_Name,Quantity,unit_price,Discount,Profit
0,cust1,Mobile,2,7000,0.10,0.15
1,cust2,Laptop,1,4000,0.05,0.20
2,cust3,Watch,5,2000,0.03,0.18
3,cust4,Laptop,6,1500,0.04,0.08
4,cust5,watch,2,5000,0.01,0.15
5,cust6,Mobile,1,8000,0.10,0.10
6,cust7,Mobile,7,1000,0.30,0.20


In [637]:
#I want know  what item purchased by cust4
#iloc
sale_data.loc[1:3,"Item_Name"]

1    Laptop
2     Watch
3    Laptop
Name: Item_Name, dtype: object

In [638]:
#loc
sale_data.iloc[1:3,1:3]

,Item_Name,Quantity
1,Laptop,1
2,Watch,5


In [639]:
#Dispaly the the 3 records from cust2
sale_data.loc[1:3,:]

,Customer_ID,Item_Name,Quantity,unit_price,Discount,Profit
1,cust2,Laptop,1,4000,0.05,0.20
2,cust3,Watch,5,2000,0.03,0.18
3,cust4,Laptop,6,1500,0.04,0.08


In [640]:
sale_data.iloc[1:4,:]

,Customer_ID,Item_Name,Quantity,unit_price,Discount,Profit
1,cust2,Laptop,1,4000,0.05,0.20
2,cust3,Watch,5,2000,0.03,0.18
3,cust4,Laptop,6,1500,0.04,0.08


In [641]:
#Dispaly the customer,ID,itemname,quantity
sale_data.iloc[:,0:3]

,Customer_ID,Item_Name,Quantity
0,cust1,Mobile,2
1,cust2,Laptop,1
2,cust3,Watch,5
3,cust4,Laptop,6
4,cust5,watch,2
5,cust6,Mobile,1
6,cust7,Mobile,7


In [642]:
sale_data[["Customer_ID","Item_Name","Quantity"]]

,Customer_ID,Item_Name,Quantity
0,cust1,Mobile,2
1,cust2,Laptop,1
2,cust3,Watch,5
3,cust4,Laptop,6
4,cust5,watch,2
5,cust6,Mobile,1
6,cust7,Mobile,7


In [643]:
#display the custom_ID,Itemname,Unit_price,Discount for cust1,3,5,7
sale_data.iloc[[0,2,4,6],[0,1,3,4]]

,Customer_ID,Item_Name,unit_price,Discount
0,cust1,Mobile,7000,0.10
2,cust3,Watch,2000,0.03
4,cust5,watch,5000,0.01
6,cust7,Mobile,1000,0.30


In [644]:
sale_data

,Customer_ID,Item_Name,Quantity,unit_price,Discount,Profit
0,cust1,Mobile,2,7000,0.10,0.15
1,cust2,Laptop,1,4000,0.05,0.20
2,cust3,Watch,5,2000,0.03,0.18
3,cust4,Laptop,6,1500,0.04,0.08
4,cust5,watch,2,5000,0.01,0.15
5,cust6,Mobile,1,8000,0.10,0.10
6,cust7,Mobile,7,1000,0.30,0.20


In [645]:
sale_data["Total_price"]=sale_data["Quantity"]*sale_data["unit_price"]
sale_data

,Customer_ID,Item_Name,Quantity,unit_price,Discount,Profit,Total_price
0,cust1,Mobile,2,7000,0.10,0.15,14000
1,cust2,Laptop,1,4000,0.05,0.20,4000
2,cust3,Watch,5,2000,0.03,0.18,10000
3,cust4,Laptop,6,1500,0.04,0.08,9000
4,cust5,watch,2,5000,0.01,0.15,10000
5,cust6,Mobile,1,8000,0.10,0.10,8000
6,cust7,Mobile,7,1000,0.30,0.20,7000


In [646]:
#How many records are prodcuing the total sale price is >=10000
(sale_data["Total_price"]>=10000).mean()

np.float64(0.42857142857142855)

In [647]:
#what are the records satisfied teh above condition
sale_data[sale_data["Total_price"]>=10000]

,Customer_ID,Item_Name,Quantity,unit_price,Discount,Profit,Total_price
0,cust1,Mobile,2,7000,0.10,0.15,14000
2,cust3,Watch,5,2000,0.03,0.18,10000
4,cust5,watch,2,5000,0.01,0.15,10000


In [648]:
#How many records are prodcuing the total sale price is >=10000 with the profit of >0.15
((sale_data["Total_price"]>=10000) & (sale_data["Profit"]>0.15)).sum()

np.int64(1)

In [649]:
sale_data[(sale_data["Total_price"]>=10000) & (sale_data["Profit"]>0.15)]

,Customer_ID,Item_Name,Quantity,unit_price,Discount,Profit,Total_price
2,cust3,Watch,5,2000,0.03,0.18,10000


In [650]:
#How many  different prodcut in item_name
sale_data["Item_Name"].nunique()

4

In [651]:
sale_data["Item_Name"].unique()

array(['Mobile', 'Laptop', 'Watch', 'watch'], dtype=object)

In [652]:
sale_data["Item_Name"].value_counts()

Item_Name
Mobile    3
Laptop    2
Watch     1
watch     1
Name: count, dtype: int64

In [653]:
#To repalce the name of the item
sale_data["Item_Name"].replace("watch","Watch",inplace=True)

C:\Users\Deepak Pandey\AppData\Local\Temp\ipykernel_2964\4103299693.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  sale_data["Item_Name"].replace("watch","Watch",inplace=True)


In [654]:
sale_data["Item_Name"].unique()

array(['Mobile', 'Laptop', 'Watch'], dtype=object)

In [655]:
sale_data["Item_Name"].value_counts()

Item_Name
Mobile    3
Laptop    2
Watch     2
Name: count, dtype: int64

In [656]:
#How much total amount spent on each item
#Mobile
sale_data[sale_data["Item_Name"]=="Mobile"].sum()

Customer_ID       cust1cust6cust7
Item_Name      MobileMobileMobile
Quantity                       10
unit_price                  16000
Discount                      0.5
Profit                       0.45
Total_price                 29000
dtype: object

In [657]:
sale_data[sale_data["Item_Name"]=="Laptop"]["Total_price"].sum()

np.int64(13000)

In [658]:
sale_data[sale_data["Item_Name"]=="Watch"]["Total_price"].sum()

np.int64(20000)

In [659]:
sale_data.groupby("Item_Name")["Total_price"].sum()

Item_Name
Laptop    13000
Mobile    29000
Watch     20000
Name: Total_price, dtype: int64

In [660]:
#sorting
sale_data.sort_values(by="Total_price",ascending=True)

,Customer_ID,Item_Name,Quantity,unit_price,Discount,Profit,Total_price
1,cust2,Laptop,1,4000,0.05,0.20,4000
6,cust7,Mobile,7,1000,0.30,0.20,7000
5,cust6,Mobile,1,8000,0.10,0.10,8000
3,cust4,Laptop,6,1500,0.04,0.08,9000
4,cust5,Watch,2,5000,0.01,0.15,10000
2,cust3,Watch,5,2000,0.03,0.18,10000
0,cust1,Mobile,2,7000,0.10,0.15,14000


In [661]:
sale_data.sort_values(by=["Total_price","Quantity"],ascending=[True,False])

,Customer_ID,Item_Name,Quantity,unit_price,Discount,Profit,Total_price
1,cust2,Laptop,1,4000,0.05,0.20,4000
6,cust7,Mobile,7,1000,0.30,0.20,7000
5,cust6,Mobile,1,8000,0.10,0.10,8000
3,cust4,Laptop,6,1500,0.04,0.08,9000
2,cust3,Watch,5,2000,0.03,0.18,10000
4,cust5,Watch,2,5000,0.01,0.15,10000
0,cust1,Mobile,2,7000,0.10,0.15,14000


In [662]:
sort_data=sale_data.sort_values(by=["Total_price","Quantity"],ascending=[True,False])
sort_data

,Customer_ID,Item_Name,Quantity,unit_price,Discount,Profit,Total_price
1,cust2,Laptop,1,4000,0.05,0.20,4000
6,cust7,Mobile,7,1000,0.30,0.20,7000
5,cust6,Mobile,1,8000,0.10,0.10,8000
3,cust4,Laptop,6,1500,0.04,0.08,9000
2,cust3,Watch,5,2000,0.03,0.18,10000
4,cust5,Watch,2,5000,0.01,0.15,10000
0,cust1,Mobile,2,7000,0.10,0.15,14000


In [663]:
sort_data.reset_index(drop=True)

,Customer_ID,Item_Name,Quantity,unit_price,Discount,Profit,Total_price
0,cust2,Laptop,1,4000,0.05,0.20,4000
1,cust7,Mobile,7,1000,0.30,0.20,7000
2,cust6,Mobile,1,8000,0.10,0.10,8000
3,cust4,Laptop,6,1500,0.04,0.08,9000
4,cust3,Watch,5,2000,0.03,0.18,10000
5,cust5,Watch,2,5000,0.01,0.15,10000
6,cust1,Mobile,2,7000,0.10,0.15,14000


In [664]:
#iterrow

In [665]:
sale_data

,Customer_ID,Item_Name,Quantity,unit_price,Discount,Profit,Total_price
0,cust1,Mobile,2,7000,0.10,0.15,14000
1,cust2,Laptop,1,4000,0.05,0.20,4000
2,cust3,Watch,5,2000,0.03,0.18,10000
3,cust4,Laptop,6,1500,0.04,0.08,9000
4,cust5,Watch,2,5000,0.01,0.15,10000
5,cust6,Mobile,1,8000,0.10,0.10,8000
6,cust7,Mobile,7,1000,0.30,0.20,7000


In [666]:
for index,row in sale_data.iterrows():
    print(f"Index :{index}")
    print(f"Customer_ID:{row['Customer_ID']},Qauntity:{row['Quantity']}")

Index :0
Customer_ID:cust1,Qauntity:2
Index :1
Customer_ID:cust2,Qauntity:1
Index :2
Customer_ID:cust3,Qauntity:5
Index :3
Customer_ID:cust4,Qauntity:6
Index :4
Customer_ID:cust5,Qauntity:2
Index :5
Customer_ID:cust6,Qauntity:1
Index :6
Customer_ID:cust7,Qauntity:7


In [667]:
# Super_store data

In [668]:
data=pd.read_excel("Super_store.xlsx")
data

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,...,Region,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID
0,18606,Not Specified,0.01,2.88,0.50,2,Janice Fletcher,Regular Air,Corporate,Office Supplies,...,Central,Illinois,Addison,60101,2012-05-28,2012-05-30,1.320000,2,5.90,88525
1,20847,High,0.01,2.84,0.93,3,Bonnie Potter,Express Air,Corporate,Office Supplies,...,West,Washington,Anacortes,98221,2010-07-07,2010-07-08,4.560000,4,13.01,88522
2,23086,Not Specified,0.03,6.68,6.15,3,Bonnie Potter,Express Air,Corporate,Office Supplies,...,West,Washington,Anacortes,98221,2011-07-27,2011-07-28,-47.640000,7,49.92,88523
3,23087,Not Specified,0.01,5.68,3.60,3,Bonnie Potter,Regular Air,Corporate,Office Supplies,...,West,Washington,Anacortes,98221,2011-07-27,2011-07-28,-30.510000,7,41.64,88523
4,23088,Not Specified,0.00,205.99,2.50,3,Bonnie Potter,Express Air,Corporate,Technology,...,West,Washington,Anacortes,98221,2011-07-27,2011-07-27,998.202300,8,1446.67,88523
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9421,20275,Critical,0.06,35.89,14.72,3402,Frederick Cole,Regular Air,Consumer,Office Supplies,...,East,West Virginia,Charleston,25314,2013-05-14,2013-05-15,137.860000,13,447.87,87532
9422,20276,Critical,0.00,3.34,7.49,3402,Frederick Cole,Regular Air,Consumer,Office Supplies,...,East,West Virginia,Charleston,25314,2013-05-14,2013-05-14,-39.070000,3,13.23,87532
9423,24491,Not Specified,0.08,550.98,45.70,3402,Frederick Cole,Delivery Truck,Consumer,Furniture,...,East,West Virginia,Charleston,25314,2013-09-12,2013-09-14,-1225.029097,4,2215.93,87533
9424,25914,High,0.10,105.98,13.99,3403,Tammy Buckley,Express Air,Consumer,Furniture,...,West,Wyoming,Cheyenne,82001,2010-02-08,2010-02-11,349.485000,5,506.50,87530


In [669]:
data.head(4)#first 5 records

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,...,Region,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID
0,18606,Not Specified,0.01,2.88,0.50,2,Janice Fletcher,Regular Air,Corporate,Office Supplies,...,Central,Illinois,Addison,60101,2012-05-28,2012-05-30,1.32,2,5.90,88525
1,20847,High,0.01,2.84,0.93,3,Bonnie Potter,Express Air,Corporate,Office Supplies,...,West,Washington,Anacortes,98221,2010-07-07,2010-07-08,4.56,4,13.01,88522
2,23086,Not Specified,0.03,6.68,6.15,3,Bonnie Potter,Express Air,Corporate,Office Supplies,...,West,Washington,Anacortes,98221,2011-07-27,2011-07-28,-47.64,7,49.92,88523
3,23087,Not Specified,0.01,5.68,3.60,3,Bonnie Potter,Regular Air,Corporate,Office Supplies,...,West,Washington,Anacortes,98221,2011-07-27,2011-07-28,-30.51,7,41.64,88523


In [670]:
data.tail()#last 5 records

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,...,Region,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID
9421,20275,Critical,0.06,35.89,14.72,3402,Frederick Cole,Regular Air,Consumer,Office Supplies,...,East,West Virginia,Charleston,25314,2013-05-14,2013-05-15,137.860000,13,447.87,87532
9422,20276,Critical,0.00,3.34,7.49,3402,Frederick Cole,Regular Air,Consumer,Office Supplies,...,East,West Virginia,Charleston,25314,2013-05-14,2013-05-14,-39.070000,3,13.23,87532
9423,24491,Not Specified,0.08,550.98,45.70,3402,Frederick Cole,Delivery Truck,Consumer,Furniture,...,East,West Virginia,Charleston,25314,2013-09-12,2013-09-14,-1225.029097,4,2215.93,87533
9424,25914,High,0.10,105.98,13.99,3403,Tammy Buckley,Express Air,Consumer,Furniture,...,West,Wyoming,Cheyenne,82001,2010-02-08,2010-02-11,349.485000,5,506.50,87530
9425,24492,Not Specified,0.09,7.78,2.50,3403,Tammy Buckley,Express Air,Consumer,Office Supplies,...,West,Wyoming,Cheyenne,82001,2013-09-12,2013-09-14,78.062400,23,172.48,87533


In [671]:
data.shape

(9426, 24)

In [672]:
data.columns

Index(['Row ID', 'Order Priority', 'Discount', 'Unit Price', 'Shipping Cost',
       'Customer ID', 'Customer Name', 'Ship Mode', 'Customer Segment',
       'Product Category', 'Product Sub-Category', 'Product Container',
       'Product Name', 'Product Base Margin', 'Region', 'State or Province',
       'City', 'Postal Code', 'Order Date', 'Ship Date', 'Profit',
       'Quantity ordered new', 'Sales', 'Order ID'],
      dtype='object')

In [673]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9426 entries, 0 to 9425
Data columns (total 24 columns):
 #   Column                Non-Null Count  Dtype         
---  ------                --------------  -----         
 0   Row ID                9426 non-null   int64         
 1   Order Priority        9426 non-null   object        
 2   Discount              9426 non-null   float64       
 3   Unit Price            9426 non-null   float64       
 4   Shipping Cost         9426 non-null   float64       
 5   Customer ID           9426 non-null   int64         
 6   Customer Name         9426 non-null   object        
 7   Ship Mode             9426 non-null   object        
 8   Customer Segment      9426 non-null   object        
 9   Product Category      9426 non-null   object        
 10  Product Sub-Category  9426 non-null   object        
 11  Product Container     9426 non-null   object        
 12  Product Name          9426 non-null   object        
 13  Product Base Margi

In [674]:
data.isnull().sum()

Row ID                   0
Order Priority           0
Discount                 0
Unit Price               0
Shipping Cost            0
Customer ID              0
Customer Name            0
Ship Mode                0
Customer Segment         0
Product Category         0
Product Sub-Category     0
Product Container        0
Product Name             0
Product Base Margin     72
Region                   0
State or Province        0
City                     0
Postal Code              0
Order Date               0
Ship Date                0
Profit                   0
Quantity ordered new     0
Sales                    0
Order ID                 0
dtype: int64

In [675]:
data.describe()#statistical behaviour of the data( FIve point summary)

,Row ID,Discount,Unit Price,Shipping Cost,Customer ID,Product Base Margin,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID
count,9426.000000,9426.000000,9426.000000,9426.000000,9426.000000,9354.000000,9426.000000,9426,9426,9426.000000,9426.000000,9426.000000,9426.000000
mean,20241.015277,0.049628,88.303686,12.795142,1738.422236,0.512189,52446.327286,2012-03-05 18:33:59.465308672,2012-03-07 19:16:18.485041408,139.236410,13.798430,949.706272,82318.489073
min,2.000000,0.000000,0.990000,0.490000,2.000000,0.350000,1001.000000,2010-01-01 00:00:00,2010-01-02 00:00:00,-16476.838000,1.000000,1.320000,6.000000
25%,19330.250000,0.020000,6.480000,3.192500,898.000000,0.380000,29406.000000,2011-03-07 06:00:00,2011-03-09 00:00:00,-74.017375,5.000000,61.282500,86737.250000
50%,21686.500000,0.050000,20.990000,6.050000,1750.000000,0.520000,52302.000000,2012-04-08 00:00:00,2012-04-09 00:00:00,2.567600,10.000000,203.455000,88344.500000
75%,24042.750000,0.080000,85.990000,13.990000,2578.750000,0.590000,78516.000000,2013-03-26 00:00:00,2013-03-28 00:00:00,140.243850,17.000000,776.402500,89987.750000
max,26399.000000,0.250000,6783.020000,164.730000,3403.000000,0.850000,99362.000000,2013-12-31 00:00:00,2014-01-17 00:00:00,16332.414000,170.000000,100119.160000,91591.000000
std,6101.890965,0.031798,281.540982,17.181203,979.167197,0.135229,29374.597802,NaN,NaN,998.486483,15.107688,2598.019818,19149.448857


In [676]:
#what is average sale in this data?
data["Sales"].mean()

np.float64(949.7062720135795)

In [677]:
#what is average profit in this data?
data["Profit"].mean()

np.float64(139.23640986926054)

In [678]:
#what is average sale and profit in this data?
data[["Sales","Profit"]].mean()

Sales     949.706272
Profit    139.236410
dtype: float64

In [679]:
# how many cities in the data?
data['City'].nunique()

1424

In [680]:
# what is the total sales in each city?
df=data.groupby('City')[['Sales','Profit']].sum()
print(df)
#data.groupby('City')["Sales"].sum()

               Sales        Profit
City                              
Aberdeen     5296.39   2411.897720
Abilene      3950.34   1436.550440
Abington       81.87    -34.088000
Acton          25.00     14.405800
Addison       496.62     25.471260
...              ...           ...
York          980.76    206.072800
Youngstown    903.24    -25.266000
Yuba City     476.43   -103.790000
Yucaipa     11027.78  -3158.736892
Yuma        19781.52  11820.745900

[1424 rows x 2 columns]


In [681]:
# what is the top 5 cities based on total sale?
city_data=data.groupby('City')["Sales"].sum()
city_data.sort_values(ascending=False).head(10)

City
New York City    534597.10
Los Angeles      515300.42
Seattle          307983.67
Chicago          229744.82
Washington       218868.62
Miami            190204.83
Philadelphia     158441.31
Boston           132614.65
Detroit          120055.20
Houston          114066.98
Name: Sales, dtype: float64

In [682]:
data.head(2)

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,...,Region,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID
0,18606,Not Specified,0.01,2.88,0.50,2,Janice Fletcher,Regular Air,Corporate,Office Supplies,...,Central,Illinois,Addison,60101,2012-05-28,2012-05-30,1.32,2,5.90,88525
1,20847,High,0.01,2.84,0.93,3,Bonnie Potter,Express Air,Corporate,Office Supplies,...,West,Washington,Anacortes,98221,2010-07-07,2010-07-08,4.56,4,13.01,88522


In [683]:
#I want to know the avg sales of each prodcut category in each region
data.groupby(["Product Category","Region"])["Sales"].mean()


Product Category  Region 
Furniture         Central    1379.161509
                  East       1803.889896
                  South      1476.381351
                  West       1971.977787
Office Supplies   Central     431.538576
                  East        559.307060
                  South       340.264359
                  West        399.814388
Technology        Central    1406.353361
                  East       1574.912342
                  South      1396.153794
                  West       1717.114056
Name: Sales, dtype: float64

In [684]:
data.groupby(["Region","Product Category"])["Sales"].mean()

Region   Product Category
Central  Furniture           1379.161509
         Office Supplies      431.538576
         Technology          1406.353361
East     Furniture           1803.889896
         Office Supplies      559.307060
         Technology          1574.912342
South    Furniture           1476.381351
         Office Supplies      340.264359
         Technology          1396.153794
West     Furniture           1971.977787
         Office Supplies      399.814388
         Technology          1717.114056
Name: Sales, dtype: float64

In [685]:
#I want to display the avg sales and profit  for each region in same table?
data.groupby("Region")[["Sales","Profit"]].mean()

,Sales,Profit
Region,,
Central,876.282035,179.312027
East,1058.455518,164.948094
South,817.475036,53.327120
West,1047.039755,136.098710


In [686]:
#I want to display the avg and sum of sales and profit  for each region in same table?
import numpy as np
data.groupby("Region").agg({"Sales":["mean","sum"],"Profit":["mean","sum","std"]})

Sales                  Profit                            
                mean         sum        mean            sum          std
Region                                                                  
Central   876.282035  2540341.62  179.312027  519825.567067   933.585650
East     1058.455518  2422804.68  164.948094  377566.186045   885.393514
South     817.475036  1597346.22   53.327120  104201.192420  1059.835314
West     1047.039755  2391438.80  136.098710  310849.453897  1119.788147

In [696]:
# dispaly the teh avg profit for the deliveries happened through different shipment mode in different region?
data.groupby(["Ship Mode","Region"])["Profit"].mean()
data.groupby(["Ship Mode","Region"])["Profit"].mean().unstack()

Region,Central,East,South,West
Ship Mode,,,,
Delivery Truck,228.070616,234.455276,141.964085,210.231767
Express Air,167.144535,139.729189,65.838272,159.111334
Regular Air,172.510164,155.558265,36.695350,118.294061


In [688]:
data[["Product Category","Ship Mode"]]

,Product Category,Ship Mode
0,Office Supplies,Regular Air
1,Office Supplies,Express Air
2,Office Supplies,Express Air
3,Office Supplies,Regular Air
4,Technology,Express Air
...,...,...
9421,Office Supplies,Regular Air
9422,Office Supplies,Regular Air
9423,Furniture,Delivery Truck
9424,Furniture,Express Air


In [689]:
# crosstab with aggregation function
pd.crosstab(data["Product Category"], data["Ship Mode"], values=data["Sales"], aggfunc="sum")

Ship Mode,Delivery Truck,Express Air,Regular Air
Product Category,,,
Furniture,2534728.38,99693.38,544201.98
Office Supplies,185447.12,280955.25,1791923.18
Technology,986340.52,321107.71,2207533.80


In [690]:
# concat and merge
df1=pd.DataFrame({"Name":["A","B","C","D"],"Age":[25,56,24,47]})
df1

,Name,Age
0,A,25
1,B,56
2,C,24
3,D,47


In [691]:
df2=pd.DataFrame({"Name":["D","B","C","A"],"Country":["US","UK","IND","CHN"]})
df2

,Name,Country
0,D,US
1,B,UK
2,C,IND
3,A,CHN


In [710]:
comb=pd.concat([df1,df2],axis=1)
comb=comb.loc[:,~comb.columns.duplicated()]  # Remove duplicate columns
comb

,Name,Age,Country
0,A,25,US
1,B,56,UK
2,C,24,IND
3,D,47,CHN


In [693]:
pd.merge(df1,df2,on="Name")

,Name,Age,Country
0,A,25,CHN
1,B,56,UK
2,C,24,IND
3,D,47,US


In [711]:
a=pd.read_csv("dataset_1.csv")
a.head()

FileNotFoundError: [Errno 2] No such file or directory: 'dataset_1.csv'

In [ ]:
a.shape

In [ ]:
b=pd.read_excel("dataset_2.xlsx")
b.head()

In [ ]:
b.shape

In [ ]:
b.drop("Unnamed: 0",axis=1,inplace=True)

In [ ]:
b.shape

In [ ]:
b.head(2)

In [ ]:
combined=pd.merge(a,b,on="instant")
combined.head(2)

In [ ]:
combined.shape

In [ ]:
c=pd.read_csv("dataset_3.csv")
c.head()

In [ ]:
c.shape

In [ ]:
final=pd.concat([combined,c])
final

In [ ]:
final.sort_values(by="instant",ascending=True).reset_index(drop=True)